name: AceOfSpadesMiniGame
version: 0.3
main: pl.grzegorz2047.aceofspadesminigame.Main
commands:
    team:
        description: wybor druzyny 1-2
    setteamspawn:
        description: ustala spawn druzyny 1-2
    aos:
        description: Komendy pluginu aoe
